# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  Chip_8_config = debug_x64

else ifeq ($(config),release_x64)
  Chip_8_config = release_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Chip-8

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Chip-8:
ifneq (,$(Chip_8_config))
	@echo "==== Building Chip-8 ($(Chip_8_config)) ===="
	@${MAKE} --no-print-directory -C . -f Chip-8.make config=$(Chip_8_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Chip-8.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Chip-8"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"